a=int(input("Enter number1 : "))
b=int(input("Enter number2 : "))
print("Addition : ",a+b)
print("subraction : ",a-b)
print("Multiplication : ",a*b)
print("Division : ",a/b)
print("Floor Division : ",a//b)
print("Modulus : ",a%b)
print("Power : ",a**b)
